### ISSUE TITLE
重新生成文件

### ISSUE THREAD

**Issue by WilliamK7** [hiifeng/V2ray-for-Replit#1]
貌似使用doprax保活的话，每次会重新生成url.txt、VLess.png及VMess.png文件

**Comment by hiifeng** [comment]
打开 main.sh，在 32-35 如下三行代码前面加 # 号，注释掉即可。

qrencode -o VMess.png $vmesslink
qrencode -o VLess.png $vlesslink

echo -e "VMess协议链接：\n$vmesslink\n\nVLess协议链接：\n$vlesslink" > url.txt
