### ISSUE TITLE
无法出墙

### ISSUE THREAD

**Issue by Toin1779712664** [hiifeng/V2ray-for-Replit#11]
配置成功了，但是无法出墙，在replit中显示的地址放入到v2ray中依旧不可使用

**Comment by hiifeng** [comment]
replit一直是正常的。有问题在群里发截图，有很多人会帮你指出问题。

**Comment by Toin1779712664** [comment]
在replit上运行这个脚本后，在本地v2ray应用软件上添加了相应的信息，依旧是无法出墙
